2022-10-08 11:05:11,504 ERROR: Exception on /index [GET] [in /home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask_login/login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 120, in login_url
    base = expand_login_view(login_view)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 97, in expand_login_view
    return url_for(login_view)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/helpers.py", line 256, in url_for
    return current_app.url_for(
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2022-10-08 11:05:31,316 INFO: Microblog startup [in /home/kali/PycharmProjects/microblog/app/__init__.py:74]
2022-10-08 11:05:59,373 INFO: Microblog startup [in /home/kali/PycharmProjects/microblog/app/__init__.py:74]
2022-10-08 11:06:02,027 ERROR: Exception on /index [GET] [in /home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask_login/login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 120, in login_url
    base = expand_login_view(login_view)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 97, in expand_login_view
    return url_for(login_view)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/helpers.py", line 256, in url_for
    return current_app.url_for(
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2022-10-08 11:06:17,659 INFO: Microblog startup [in /home/kali/PycharmProjects/microblog/app/__init__.py:74]
2022-10-08 11:07:14,051 INFO: Microblog startup [in /home/kali/PycharmProjects/microblog/app/__init__.py:74]
2022-10-08 11:07:16,820 ERROR: Exception on /index [GET] [in /home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask_login/login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 120, in login_url
    base = expand_login_view(login_view)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask_login/utils.py", line 97, in expand_login_view
    return url_for(login_view)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/helpers.py", line 256, in url_for
    return current_app.url_for(
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/flask/app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/kali/PycharmProjects/microblog/venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2022-10-08 11:07:37,789 INFO: Microblog startup [in /home/kali/PycharmProjects/microblog/app/__init__.py:74]
2022-10-08 11:16:00,982 INFO: Microblog startup [in /home/kali/PycharmProjects/microblog/app/__init__.py:74]
2022-10-08 14:09:18,539 INFO: Microblog startup [in /home/kali/PycharmProjects/microblog/app/__init__.py:74]
2022-10-08 18:29:51,682 INFO: Microblog startup [in /home/kali/PycharmProjects/microblog/app/__init__.py:74]
2022-10-08 22:14:19,000 INFO: Microblog startup [in /home/kali/PycharmProjects/microblog/app/__init__.py:74]
2022-10-09 10:13:42,189 INFO: Microblog startup [in /home/kali/PycharmProjects/microblog/app/__init__.py:74]
2022-10-09 10:25:37,514 INFO: Microblog startup [in /home/kali/PycharmProjects/microblog/app/__init__.py:74]
2022-10-09 20:58:54,901 INFO: Microblog startup [in /home/kali/PycharmProjects/microblog/app/__init__.py:78]
2022-10-09 23:24:36,525 INFO: Microblog startup [in /home/kali/PycharmProjects/microblog/app/__init__.py:78]
